### ISSUE TITLE
Add no color option for fill and line

### ISSUE THREAD

**Issue by makella** [nationalparkservice/npmap-builder#108]
When adding a polygon overlay, it would be nice to specify either no fill or no line color -- for the cases when you want to either only symbolize the line or the fill .
Right now the way to do that is to make either the line or fill totally transparent - but the lowest transparency option is still not fully transparent.
Example - I'd like to remove the fill from the I&M Networks:
![builder](https://cloud.githubusercontent.com/assets/1566273/2973687/1509a79e-db80-11e3-93b8-60eadeac0537.png)

**Comment by nateirwin** [comment]
This is now possible by setting the opacity to 0. We should improve the color picker and add a "no color" option in the future, but hopefully this will suffice for now.
