### ISSUE TITLE
Possible to enable ruler tool in areas with tooltips?

### ISSUE THREAD

**Issue by alexNPS** [nationalparkservice/npmap-builder#110]
mapId=3b15ffde-1295-40f3-8e61-888d34c0ed5d is my map; its purpose is to illustrate the backcountry units of the park and link over to pages with more details about each. 

I thought it'd be kind of neat to include the ruler tool, so people could more easily estimate distances; but realized today that the polygons are clickable, so the ruler cannot be used on those parts of the map. Is there a way to allow my users to hide the polygon layers and thus use the ruler right on the base map? (Or some other solution that I'm not thinking of?)

Thanks! No worries if the best answer is just "no," that's understandable.

alex

**Comment by nateirwin** [comment]
This is now fixed in NPMap.js, and Builder will reflect the fix sometime tomorrow.
