### ISSUE TITLE
Internet Explorer 11 rendering issue

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-builder#127]
When loading a Map Builder map in Internet Exploder 11 (Version 11.0.9600.17126), the extent and XY center is shifted up, in addition, most of the tiles are not rendered. First image shows http://www.nps.gov/maps/full.html?mapId=cb728c24-adf8-4fb9-a7a0-d27a0b1a13d4 on initial page load. Second image shows same in Chrome. This is on a non-park-owned computer, with none of the IT security "enhancements" enabled. Tried with firewall and AV turned off, same result. 

However, MINIMIZING the IE window, or resizing it, defaults back to expected behavior. 

Windows 7 64-bit. Fiddler trace shows nothing different during page load of both browsers.

![iell](https://cloud.githubusercontent.com/assets/5861784/3450733/64701e02-0183-11e4-8c90-8b634ec52145.JPG)

![grome](https://cloud.githubusercontent.com/assets/5861784/3450737/893cfb88-0183-11e4-891f-f38b5bb8d089.JPG)

**Comment by nateirwin** [comment]
This will be fixed once we migrate NPMap.js to Leaflet 1.

**Comment by nateirwin** [comment]
This was recently fixed in NPMap.js, so closing.
