### ISSUE TITLE
Is there a Handlebars helper for formatting date?

### ISSUE THREAD

**Issue by alexNPS** [nationalparkservice/npmap-builder#172]
I'm working on mapId=cc882ba4-e062-45e2-8241-4adce1552d16. 

The SPOT device returns a bunch of unhelpful data, but at least I have dateTime to work with - however, you'll see it returns it in a format like 2014-10-08T21:07:37+0000.

I tried reading a bit to see if I could sort out on my own how to format it, and it seems like there are dateTime helpers for Mustache and Handlebars, but I don't quite know enough on how (or exactly what) to implement. I'm pretty flexible on the actual output, so long as it's readable (e.g., anything like HH:MM-Month-Day-Year, or whatever the ISO format for dates and times is).

Nate has helped me with this one already, but that was before SPOT was a supported data source within Builder. Now that the map is done through the Builder, I was hoping to figure it out on my own, but without any success. Is this something I should be able to configure on my own, or will I have to bug you guys to do it for me?

Thanks!

**Comment by alexNPS** [comment]
Hey Nate, I thought I'd bump this to see if you had a chance to think about it a bit more. Our mushers are heading on a thousand mile trip to Nome (though not as part of the Iditarod) in a month or so, and I'd love to be able to polish the map up a bit if I could. 

No stress if you haven't gotten back to it, though.

**Comment by nateirwin** [comment]
Sorry about taking so long to get to this. I kept on putting it off because the moment Handlebars helpers was pretty bulky; it added ~46kb to the overall library, and I didn't think the tradeoff was worth it. I ended up going with another library: https://github.com/nationalparkservice/helper-dateformat. It isn't as full-featured as the moment helper, but it should do the job.

Take a look at this example for more information on how to use this helper in your popup/tooltip configuration: https://github.com/nationalparkservice/npmap.js/blob/88729420eb846e475697062aac7f6730670614dd/examples/handlebars.html.

**Comment by alexNPS** [comment]
Thanks Nate!

Do I by chance need to delete and then re-add my data layer or anything
else to take advantage of this new helper? I've tried simply pasting

{{dateFormat "dddd, mmmm dS, yyyy, h:MM:ss TT" dateTime}}

into my info box, but it does not like that config code (i.e., clicking on
points does not open the info box).


On Thu, Feb 19, 2015 at 12:14 PM, Nate Irwin <notifications@github.com>
wrote:

> Closed #172
> <https://github.com/nationalparkservice/npmap-builder/issues/172>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/npmap-builder/issues/172#event-238702018>
> .
>



-- 

Alex Lindeman

Visual Information Specialist / Alaska Region Web Coordinator
Denali National Park and Preserve
(907) 683-6392 (o)
(907) 378-0366 (c)

**Comment by nateirwin** [comment]
Oops! Try changing the double quotes (`"`) to single quotes (`'`).

**Comment by nateirwin** [comment]
BTW, this is necessary in Builder because it handles popup/tooltip configs slightly differently than NPMap.js does. We probably need to automate cleanup so this is transparent, but for now just use single quotes for most things.

**Comment by alexNPS** [comment]
Hmm, I wont be surprised if it's user error, but I still get nothing with
{{dateFormat 'dddd, mmmm dS, yyyy, h:MM:ss TT' dateTime}}

On Thu, Feb 19, 2015 at 12:51 PM, Nate Irwin <notifications@github.com>
wrote:

> BTW, this is necessary in Builder because it handles popup/tooltip configs
> slightly differently than NPMap.js does. We probably need to automate
> cleanup so this is transparent, but for now just use single quotes for most
> things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/npmap-builder/issues/172#issuecomment-75145839>
> .
>



-- 

Alex Lindeman

Visual Information Specialist / Alaska Region Web Coordinator
Denali National Park and Preserve
(907) 683-6392 (o)
(907) 378-0366 (c)

**Comment by nateirwin** [comment]
It's probably something stuck in your cache. Can you clear your browser cache and try one more time? I just tried, and it worked with a fresh cache in Chrome.

**Comment by alexNPS** [comment]
Exactly right, as always. Thanks, Nate! It's working great for me now.

best -

On Thu, Feb 19, 2015 at 1:06 PM, Nate Irwin <notifications@github.com>
wrote:

> It's probably something stuck in your cache. Can you clear your browser
> cache and try one more time? I just tried, and it worked with a fresh cache
> in Chrome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/npmap-builder/issues/172#issuecomment-75148520>
> .
>



-- 

Alex Lindeman

Visual Information Specialist / Alaska Region Web Coordinator
Denali National Park and Preserve
(907) 683-6392 (o)
(907) 378-0366 (c)

**Comment by nateirwin** [comment]
Great! Let us know if you run into any more problems.
