### ISSUE TITLE
changing overlay order locks color editing and removes symbology for features 

### ISSUE THREAD

**Issue by makella** [nationalparkservice/npmap-builder#181]
I've been testing the new color implementation this morning with CartoDB tables.  I added four different tables (trails, roads, park boundary, and buildings), styled trails, buildings, and boundary then added roads, changed the drawing order of the overlays.  

After I did this, the symbology I had set for trails and buildings is no longer showing on the map and the color setting for roads is locked (the symbol window doesn't pop up):
![screen shot 2014-12-16 at 9 11 52 am](https://cloud.githubusercontent.com/assets/1566273/5456832/a56b25a6-8503-11e4-865e-3addfffd8e6a.png)

When I click on another feature like trails, the symbol window pops up but has defaulted back to original color.  I can change the color and other settings but when I click Apply to change the color, the window sticks and the map isn't updated:

![screen shot 2014-12-16 at 9 11 19 am](https://cloud.githubusercontent.com/assets/1566273/5456819/81d6bc4a-8503-11e4-81c0-a43ee6f85947.png)

The map id is: c3d17f97-1466-4d30-ba20-f589473c7478

**Comment by nateirwin** [comment]
Fixed. @tpcolson: This should fix a problem you were having too.
