### ISSUE TITLE
Transparency for image services

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-builder#184]
When adding a hosted image services such as from http://foresthealth.fs.usda.gov/arcgisfh/rest/services/NIDRM_Map/Exotics/MapServer, allow editor to either control transparency at build-time or include user slide-bar at run time.

**Comment by nateirwin** [comment]
You can define the opacity in the “edit overlay” dialog.

![map___builder___insidemaps___national_park_service](https://cloud.githubusercontent.com/assets/10443/6021568/0a0ccd3e-ab74-11e4-9976-15d9c63abe6c.png)

I just surfaced your request for a opacity control up to NPMap.js. You can track it there: https://github.com/nationalparkservice/npmap.js/issues/187.
