### ISSUE TITLE
Support changing color by polygon attribute - geojson

### ISSUE THREAD

**Issue by johnpauls** [nationalparkservice/npmap-builder#189]
I recently made a test map from a geojson file - shown here:

http://www.nps.gov/maps/embed.html?mapId=8088de36-5487-4964-baf6-6aa979fe0e47

I would like change the polygon colors so they vary based on the "MapClass" field, but there does not seem to be a way to do this.

**Comment by MappingKat** [comment]
Hey @johnpauls,

Unfortunately, we do not yet have an easy way to do this yet.

One way that I work around this is to separate the data and then add and style it separately.

**Comment by johnpauls** [comment]
Thanks for the suggestion. This came up as I am trying out different ESRI shapefile -> NPMap workflows that don't involve having an account on a arcgis server. I will see if I can come up with an easier KML workflow.

**Comment by MappingKat** [comment]
I think the easiest method is to use CartoDB and put all of your data in one table and then just add different layers with different SQL Queries.  You can create a free account at CartoDB and test it out.

**Comment by nateirwin** [comment]
Hi @johnpauls: Yes, currently the easiest way to do this is to separate the data into separate "overlays" and then style them individually. There is already an open ticket, #146, for addressing this issue, so I'm going to close this one for now. If you have other questions about this, post them back in this thread.
