### ISSUE TITLE
Overview map overwhelms mobile device screens

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-builder#199]
When the over view map is enabled, upon display on a mobile device the overview map "box" consumes a substantial amount of screen real-estate such that the main map cannot be seen. 

Overview map should have an "X" close icon, which is obvious, so it can be turned off at run time on mobile devices. The current tiny "arrow" that does this is not so obvious. Alternatively the overview map could be minimized by default on mobile devices.

**Comment by nateirwin** [comment]
This is kind of fixed. NPMap.js now hides the overview control on smaller viewports. That said, I'm going to leave this open for now, as I really want to clean this up so the control shrinks rather than hides on smaller devices.

**Comment by nateirwin** [comment]
This was fixed awhile back in NPMap.js, so closing here.
