### ISSUE TITLE
Add "AED" Icon

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-builder#202]
Add "AED" Icon to MAKI or NPS icon to Builder. AED symbology consists of variations of a "Heart" with a "Lightening Bolt" through it. http://blog.pacificlegal.org/wp/wp-content/uploads/2014/04/aed_sign-web.gif

**Comment by nateirwin** [comment]
I opened a new issue upstream in NPMaki: https://github.com/nationalparkservice/npmaki/issues/5. Will close here, as the icon will be automatically pulled in when NPMaki is updated.
