### ISSUE TITLE
Can't cluster geojson

### ISSUE THREAD

**Issue by makella** [nationalparkservice/npmap-builder#207]
When I click on the option to cluster in Builder, the option for adding the overlay grays out. If I uncheck that option, then I am able to add the overlay.

Here is the data I am trying to cluster:
https://raw.githubusercontent.com/makella/symbol_test/master/park_points.geojson

And the Builder map id:
mapId=a1fea381-5e4d-4245-b9ba-98c0bcabb393

**Comment by nateirwin** [comment]
Just tried to reproduce with that same dataset, and was unable to. Going to go ahead and close for now.
