### ISSUE TITLE
Add custom zoom levels

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-builder#213]
I'm sure there's no solution for this, but....

For GRSM, there is no zoom level that will "appropriately" show the park boundary. For example in http://www.nps.gov/grsm/planyourvisit/eatingsleeping.htm at Zoom 9, the park is zoomed "out too much" and zoom 10 truncates the park. If there was any way we could zoom level 9.5.......

**Comment by jakecoolidge** [comment]
The size of the page div is the constraint that affects how much of the park is visible at the zoom level. What if you had a map that could be expanded to occupy more screen space? Something like the map found [here,](http://www.nps.gov/npmap/blog/park-tiles-slate.html) under "Take a look"?

**Comment by tpcolson** [comment]
I'm not sure what you mean by expanding to more screen space?

**Comment by makella** [comment]
Hey Tom, one enhancement that is coming soon to Leaflet is the ability to do half zooms... once this feature is implemented there, we'll implement into npmap.js.

**Comment by nateirwin** [comment]
Closing this one, as there are two enhancements coming that will address this:

- As @makella mentions, Leaflet 1 will support incremental zooms
- #216
