### ISSUE TITLE
Label artifacts at zoom level 9

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-builder#214]
Label artifacts at zoom level 9: In http://www.nps.gov/grsm/planyourvisit/waterfalls.htm, at the "Home" zoom level, a label artifact occurs in the south-central area of the  map. See "Smokemont", which, at that zoom level, renders as "kemont". This also occurs with Park Tile Slate.

**Comment by makella** [comment]
Hi Tom, I'm going to move this over to Park Tiles as an issue.  I'll look into it more and let you know what I find out.  I'm out of the office this week so it might not be until next week.

Thanks for pointing this out.

**Comment by makella** [comment]
@tpcolson this should be fixed now.
