### ISSUE TITLE
When Builder Map is in CMS, scrolling can grab mouse focus

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-builder#215]
http://www.nps.gov/grsm/planyourvisit/waterfalls.htm

When using the mouse wheel to scroll a NPS page manged by CMS, if a user (visitor) inadvertently moves the mouse over the Builder Map while scrolling, page scrolling stops and map zooming starts. 

Map zooming using the mouse wheel shouldn't occur unless the user has clicked within the map div frame and intends to zoom. 

Page scrolling should function as the visitor intended unless mouse focus is deliberately clicked on the map div frame.

**Comment by ryanjhodge** [comment]
Hey I recently dealt with this myself in an embedded SharePoint map, I just disabled scrolling by unchecking the scroll wheel zoom option in Builder.
![capture](https://cloud.githubusercontent.com/assets/4172213/7710047/08430686-fe16-11e4-9207-ca6bad1e35b9.PNG)

The user can only zoom in/out with the zoom buttons under this configuration. Is this the behavior you want? or are you requesting an enhancement that works the way you are suggesting?

**Comment by tpcolson** [comment]
Unfortunately, the zoom by mouse wheel scroll is an in-demand option, so we need to leave that checked. I'd classify this as an enhancement.

**Comment by nateirwin** [comment]
This is tricky. First of all, you can't dynamically change the scrollwheel behavior of a Leaflet map. This may be supported in Leaflet 1.0, but I'm not sure.

Secondly, even if we could dynamically change the scrollwheel behavior, I don't know that this would work intuitively in practice. We might be able to enable scrollwheel when the map has focus, but this behavior would be different than pretty much every single web map that is out there.

Thirdly, our accessibility audit recommended that we disable scrollwheelzoom by default, as it hinders accessibility (and usability) in many cases. We are going to make this change in NPMap.js 2.1.0.

Given all this, I'm inclined to close this and tag it `wont-fix`. I understand that there may be an issue for certain maps, but, like @ryanjhodge mentions above, the recommended approach is disabling scrollwheelzoom altogether.
