### ISSUE TITLE
CartoDB date fields do not show in popups

### ISSUE THREAD

**Issue by regan-sarwas** [nationalparkservice/npmap-builder#222]
Compare the popup on a cartodb layer with user: *nps-akro-gis* table: *animal_locations* with

[https://nps-akro-gis.cartodb.com/api/v2/sql?q=select * from animal_locations limit 1](https://nps-akro-gis.cartodb.com/api/v2/sql?q=select * from animal_locations limit 1)

In this case the fixdate column is an important user attribute

**Comment by ryanjhodge** [comment]
Hey @regan-sarwas,

Looks like this an [issue with mapnik](https://github.com/CartoDB/Windshaft/issues/103), and the [workaround](https://github.com/CartoDB/cartodb/issues/3614) is to cast any postgres date fields as text.

Just copy the NPMap configuration code from builder and add these two parameters to the cartodb layer configuration object
```
interactivity: "projectid,animalid,fixdate,fixid,cartodb_id",
sql: "SELECT cartodb_id, projectid, animalid, fixid, to_char(fixdate,'YYYY-MM-DD-HH12:MI:SS') as fixdate, the_geom_webmercator FROM animal_locations"
```
Just make sure you specify all the fields that you want to show up in `interactivity` and then make sure they are all included in the `sql` statement

Here's a [working example](http://bl.ocks.org/ryanjhodge/5e8dbfe410b9d66d4c4a)

Here's the `to_char()` postgres [resource page](http://www.postgresql.org/docs/9.4/static/functions-formatting.html)

**Comment by nateirwin** [comment]
Thanks, @ryanjhodge! Looks like that is the problem.

Do you think we should roll this up into NPMap.js? We already do a simple query when a CartoDB layer is created to get the field definitions for the layer: https://github.com/nationalparkservice/npmap.js/blob/master/src/layer/cartodb.js#L149. So we know which ones are date fields. We could automatically handle the `to_char` conversion internally.

**Comment by alexNPS** [comment]
Hey guys - 

@nateirwin, is this something that could be possible in Builder? It looks, right now, like @ryanjhodge's recommendation works only if you're creating your NPMap outside of Builder (though, maybe I'm mistaken on that assumption).

**Comment by nateirwin** [comment]
@alexNPS: Yes, if we integrate this into NPMap.js, the change will automatically roll down to Builder. I'm going to go ahead and open an issue in the NPMap.js issue tracker, and then I'll close both issues once this is resolved.

**Comment by alexNPS** [comment]
Awesomeness, thank you!

On Tue, Jul 7, 2015 at 11:54 AM, Nate Irwin <notifications@github.com>
wrote:

> @alexNPS <https://github.com/alexNPS>: Yes, if we integrate this into
> NPMap.js, the change will automatically roll down to Builder. I'm going to
> go ahead and open an issue in the NPMap.js issue tracker, and then I'll
> close both issues once this is resolved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/npmap-builder/issues/222#issuecomment-119317033>
> .
>



-- 

Alex Lindeman

Visual Information Specialist / Alaska Region Web Coordinator
Denali National Park and Preserve
(907) 683-6392 (o)
(907) 378-0366 (c)

**Comment by ryanjhodge** [comment]
Ive been out in the field monitoring springs the last few days, but I was
planning on looking into this during the weekend.

**Comment by nateirwin** [comment]
This is still an issue. We are waiting on CartoDB to fix an internal bug. Tracking in NPMap.js here: https://github.com/nationalparkservice/npmap.js/issues/227, but I'll keep this issue updated, as well.

**Comment by nateirwin** [comment]
Thanks to @ryanjhodge, this is now fixed in NPMap.js. We'll need to tag a new release and upgrade Builder before this is available in Builder, however. I'll try to get a new release out tomorrow when I get back into the office. I'll leave this issue open until then.

**Comment by nateirwin** [comment]
This is finally fixed! Thanks all for your help.

![map___builder___insidemaps___national_park_service](https://cloud.githubusercontent.com/assets/10443/10823309/b5e39bd6-7e20-11e5-88db-cbbb6533907c.jpg)
