### ISSUE TITLE
Add an Existing Overlay window not closing

### ISSUE THREAD

**Issue by makella** [nationalparkservice/npmap-builder#223]
I'm making a Builder map with a Mapbox overlay and when I hit Add to Map, it adds the layer but the window does not close and defaults back to a new Add an Existing Overlay state.  I can see that my layer has been added in the background.

Trying to close the window or hit Cancel does not do anything.  

<img width="1360" alt="screen shot 2015-07-07 at 3 45 09 pm" src="https://cloud.githubusercontent.com/assets/1566273/8558145/89f6dca0-24bf-11e5-9365-abfeb940c71e.png">

**Comment by nateirwin** [comment]
Uh oh. Are you using Chrome? Can you send me the Mapbox ID too?

**Comment by makella** [comment]
Yeah in Chrome.  id: nps.345f2a18

**Comment by makella** [comment]
It is working now.  I had to clear my browser's cache.
