### ISSUE TITLE
SQL query - LIKE and wildcards supported?

### ISSUE THREAD

**Issue by alex-lindeman** [nationalparkservice/npmap-builder#226]
Hey - 
Sorry if this is another silly question. I'm trying to drawn from a carto table owned by nps-akro-gis called animal_locations. I want to filter data by animalid and fixdate (to narrow the results down to a certain date range, e.g., July). 

I've tried SELECT * FROM animal_locations WHERE animalid='055' AND fixdate LIKE '2015-06%' but I get an error. I've tried to just use the phrase WHERE fixdate LIKE '2015-07-%' too, but get an error there, too. So I'm thinking either the LIKE statement or my wildcard is the issue, but I'm also thinking I'm not confident in that self-assessment.

No rush, but thanks for any advice you might offer.

**Comment by regan-sarwas** [comment]
@alex-lindeman try SELECT * FROM animal_locations WHERE animalid='055' AND fixdate >= '2015-07-01' AND fixdate <  '2015-08-01'

**Comment by alex-lindeman** [comment]
That did it, thanks so much Regan!

On Mon, Jul 27, 2015 at 1:47 PM, Regan Sarwas <notifications@github.com>
wrote:

> @alex-lindeman <https://github.com/alex-lindeman> try SELECT * FROM
> animal_locations WHERE animalid='055' AND fixdate >= '2015-07-01' AND
> fixdate < '2015-08-01'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/npmap-builder/issues/226#issuecomment-125351453>
> .
>



-- 

Alex Lindeman

Visual Information Specialist / Alaska Region Web Coordinator
Denali National Park and Preserve
(907) 683-6392 (o)
(907) 378-0366 (c)
