### ISSUE TITLE
Builder not recognizing when logged into NPS network

### ISSUE THREAD

**Issue by makella** [nationalparkservice/npmap-builder#227]
Mark Christiano pointed out this morning that Builder maps aren't saving.  When attempting to save, the following message appears: 
![screen shot 2015-08-03 at 7 27 52 am](https://cloud.githubusercontent.com/assets/1566273/9038399/24ba6260-39b1-11e5-90ad-2b9a0180fec4.png)

I tried it this morning too and am getting the same error.

**Comment by nateirwin** [comment]
I figured out what this is. Apparently a lot of accounts were changed over the weekend internally, and this is causing writes from Builder to fail. I'm working with IT support on the issue.

**Comment by nateirwin** [comment]
Ok, this is fixed. I had to delete ~10 maps that people tried to save unsuccessfully.
