### ISSUE TITLE
include add feature services functionality to Builder

### ISSUE THREAD

**Issue by njander** [nationalparkservice/npmap-builder#232]
I would really like to be able to add feature services from AGOL or ArcGIS server into a map using the Builder interface.

Thanks!

Neal

**Comment by nateirwin** [comment]
Hi Neal, you can currently add features from a feature service hosted on ArcGIS Online to your Builder map. Just select `GeoJSON` as the layer type and then append `?f=geojson` to the URL of your service. Here's a full example of a URL:

`http://services1.arcgis.com/fBc8EJBxQRMcHlei/ArcGIS/rest/services/GRSM_RESTROOMS/FeatureServer/0/query?outSR=4326&where=OBJECTID+IS+NOT+NULL&f=geojson`

For feature services served from an ArcGIS Server instance, you can run them through a proxy. Again, you would select `GeoJSON` as the layer type and then run them through a proxy like this:

`https://server-utils.herokuapp.com/arcgis2geojson/?url=http://mapservices.nps.gov/arcgis/rest/services/LandResourcesDivisionTractAndBoundaryService/MapServer/1`

Just be careful with this. As you know, feature services return data as vectors, not rasters, so there is a limit to what your map will be able to handle. For example, if you need to display complex polygons or datasets with thousands of records, you'll probably want to stick with a map service for performance reasons.

I'm going to go ahead and close this issue, but feel free to respond here if you run into any problems or have any questions.
