### ISSUE TITLE
add recent parks to search function

### ISSUE THREAD

**Issue by bmclane-NPS** [nationalparkservice/npmap-builder#237]
A number of new parks are missing from the search bar function:

- Manhattan Project National Historical Park (all 3 units)
- Harriet Tubman Underground Railroad National Monument
- Hanouliuli National Monument
- Tule Springs National Monument
- Pullman National Monument

It would be great to add these. Thanks!

**Comment by nateirwin** [comment]
Thanks, @bmclane-NPS. We have an open ticket that should address this problem: https://github.com/nationalparkservice/npmap.js/issues/112. I'm going to try to take a look at this in the next day or so, and will update this issue then.

**Comment by nateirwin** [comment]
Ok, this is fixed in NPMap.js now. We'll need to release a new version of NPMap.js and bump NPMap Builder to it to get these new parks in. I'll try to get to it tomorrow. I'll come back and update this ticket when it is all ready.

**Comment by nateirwin** [comment]
This is now available in NPMap Builder. The problem now is we don't have boundary files for the first four on your list. I've opened another issue in our places-data repository. That's where we track boundary issues: https://github.com/nationalparkservice/places-data/issues/176. Going to close this issue.

**Comment by bmclane-NPS** [comment]
I dont think Lands has created a boundary yet!

Thanks,

Brenden

*Brenden Mclane*
*Cartographer*
*WASO Park Cultural Landscapes Program*
*PWR GIS Group*
National Park Service
Pacific West Regional Office
Seattle, WA
brenden_mclane@nps.gov
(206) 220-4135

Office Hours (PST):
*Monday; **8:00 AM - 4:30 PM*
*Tuesday; **8:00 AM - 4:30 PM*
*Wednesday; 8:00 AM - 4:30 PM*
*Thursday; **8:00 AM - 4:30 PM*
*Friday; **7:30 AM - 4:00 PM (work from home, please email)*
