### ISSUE TITLE
Add author info to gallery page

### ISSUE THREAD

**Issue by frogmapr** [nationalparkservice/npmap-builder#241]
Right now, there are quite a few maps available on the builder gallery but if I understand correctly, there is no way from the builder gallery for me to see who created a particular map unless they put their name / contact info into the description.

Am I missing something?
I would find it useful to have an author column so that I could contact other map makers in the park service for questions on how they made their map etc.
Thanks!  Neal

**Comment by nateirwin** [comment]
Hi, @frogmapr. This one has been on the list for awhile. It should be fairly to implement, so we'll try to prioritize it.

**Comment by nateirwin** [comment]
Done.
