### ISSUE TITLE
Build a map stalling after title creation

### ISSUE THREAD

**Issue by cwlawlis802** [nationalparkservice/npmap-builder#242]
When creating a new map, builder is stalling after adding a title. Typically it would bring you to the next prompt to acknowledge the disclaimer. The screen is grey and locked.

![map builder insidemaps national park service 2015-10-15 09-51-54](https://cloud.githubusercontent.com/assets/1238636/10519328/672c2246-7322-11e5-85b2-484c8b71a193.jpg)

**Comment by nateirwin** [comment]
Fixed.
