### ISSUE TITLE
NPMap displaying weirdly in the CMS (but no others have this issue)

### ISSUE THREAD

**Issue by alex-lindeman** [nationalparkservice/npmap-builder#243]
Map fd8af786-2620-4ae6-86ec-9836d6f2bb80 is displaying really weirdly in the CMS. No other map is having this issue. 

This map in question isn't even appearing on YUCH's site - we've tried placing it on multiple pages, and it just shows the description of the map in green header (subheader?) text within the NPMap element.

On DENA, at www.nps.gov/dena/map-test.htm, you'll see two maps displaying just fine, and this third map displaying funky - it shows up, unlike on YUCH, but it is still showing the description as green header text.

**Comment by nateirwin** [comment]
Hi, @alex-lindeman. I can't seem to reproduce. In Chrome, all of the maps are displaying fine for me. Can you post a screenshot of what you're seeing?

**Comment by alex-lindeman** [comment]
Hey -

Take a look at www.nps.gov/dena/new-map-test.htm, I just made that dummy
page public for now and will delete after you have a chance to investigate.

Thanks!

On Thu, Oct 22, 2015 at 9:25 AM, Nate Irwin <notifications@github.com>
wrote:

> Hi, @alex-lindeman <https://github.com/alex-lindeman>. I can't seem to
> reproduce. In Chrome, all of the maps are displaying fine for me. Can you
> post a screenshot of what you're seeing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/npmap-builder/issues/243#issuecomment-150297022>
> .
>



-- 

Alex Lindeman

Visual Information Specialist / Alaska Region Web Coordinator
Denali National Park and Preserve
(907) 683-6392 (o)
(907) 378-0366 (c)

**Comment by nateirwin** [comment]
Looks good to me?

**Comment by alex-lindeman** [comment]
Maybe the styling changed universally? I remember the dark green text being
the map title, and then the map description was in gray text below the map.
Now, the title isn't displaying anywhere and the description text from
Builder is being displayed in the subheading font / style above the map.
Perhaps that means it's a WSD issue?

On Fri, Oct 23, 2015 at 10:55 AM, Nate Irwin <notifications@github.com>
wrote:

> Looks good to me?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/npmap-builder/issues/243#issuecomment-150662840>
> .
>



-- 

Alex Lindeman

Visual Information Specialist / Alaska Region Web Coordinator
Denali National Park and Preserve
(907) 683-6392 (o)
(907) 378-0366 (c)

**Comment by nateirwin** [comment]
Ah, I see what you're talking about. That is actually all controlled on the CMS side, so maybe some styles were updated there?

**Comment by alex-lindeman** [comment]
Not to worry - I will submit a ticket to WSD. Thank you!

On Fri, Oct 23, 2015 at 11:04 AM, Nate Irwin <notifications@github.com>
wrote:

> Ah, I see what you're talking about. That is actually all controlled on
> the CMS side, so maybe some styles were updated there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/npmap-builder/issues/243#issuecomment-150664916>
> .
>



-- 

Alex Lindeman

Visual Information Specialist / Alaska Region Web Coordinator
Denali National Park and Preserve
(907) 683-6392 (o)
(907) 378-0366 (c)
