### ISSUE TITLE
my builder maps not showing up

### ISSUE THREAD

**Issue by frogmapr** [nationalparkservice/npmap-builder#246]
Hi, Just wanted to inform you that my builder maps were not showing up in the my buider UI today. attached is the screen shot.  Thanks!  

![builderlistissuenj1](https://cloud.githubusercontent.com/assets/11652263/11132098/59843e96-894b-11e5-8628-ee38c68af044.jpg)

**Comment by nateirwin** [comment]
Yes, Web Services Division is having delivery server issues right now. These issues are affecting all Builder maps and many public-facing NPS.gov sites :-(

**Comment by nateirwin** [comment]
This should be fixed now.
