### ISSUE TITLE
Add INaturalist Support

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-builder#248]
Add INaturalist Support by adding as a "Data Source" thingy, observation locations coming from the INaturalist JSON api.

**Comment by nateirwin** [comment]
Is there any documentation for this API?

**Comment by tpcolson** [comment]
https://www.inaturalist.org/pages/api+reference#get-observations

I'm just tilting at windmills here, but as "BioBlitzs" ramp up as part of centennial, I see a demand to be able to see these observations in a map, this seems like the quickest way.

**Comment by ryanjhodge** [comment]
I like this idea.  We're involved with the data management portion of our NCCN BioBlitz as well.

On the webinar last week, @simonkingston said that they will be creating a new iNaturalist "Project" for each individual BioBlitz.

The `observations/projects/:id` end point can return data for a project in KML format.  See some pilot work here: http://jsfiddle.net/ryanjhodge/euktq0z9/

The popups just need some sprucing up, which is easy to do. Any thoughts/ideas on how to implement this? Think it would warrant a special iNaturalist layer handler? or perhaps just a template NPMap config object in which only the kml URL needs to be updated.

[API reference for `observations/projects/:id`](https://www.inaturalist.org/pages/api+reference#get-observations-project-id)
[Available Params for `observations` End Point](https://www.inaturalist.org/pages/api+reference#get-observations)

**Comment by nateirwin** [comment]
I think this should be a "preset" like the Places button. Should be easy to do.

**Comment by ryanjhodge** [comment]
Sounds good, I'd be glad to give the preset button a go.

**Comment by nateirwin** [comment]
Cool! The code is in here: https://github.com/nationalparkservice/npmap-builder/tree/master/ui/modal. You'll be working in `addLayer.css`, `addLayer.html`, and `addLayer.js`.

**Comment by simonkingston** [comment]
Hi all,

It would be good to talk about where/how you're intending to present this information.  I love the idea of making iNaturalist observations more visible to park folks.

**Comment by nateirwin** [comment]
Great, @simonkingston! Want to jump on a quick call to discuss? I'm on leave through next Monday, but could do later in the week. How about you, @ryanjhodge?

Cc/ @tpcolson

**Comment by simonkingston** [comment]
Sure @nateirwin.  I'm available for the next 2 hours today and from 10am - 2pm tomorrow.  Might want to rope Pete Budde into the conversation too - he's been my partner in crime for data mgmt. at the big bioblitzes.  Looks like @ryanjhodge is in a meeting until 3pm Mountain time, but may be free after that?

**Comment by tpcolson** [comment]
I don't have a lot of openings 'till next week......

**Comment by simonkingston** [comment]
In the meantime, it would be helpful to understand what the goals are, what anticipated use cases you have (e.g., park NR staff want to be able to X, public wants to do Y), and where you intended to display the maps. @tpcolson @ryanjhodge

**Comment by nateirwin** [comment]
Yeah, perhaps we can start the conversation here and carry it to a call if/when needed.

**Comment by ryanjhodge** [comment]
Sounds like a good strategy.

**NR Staff**
We have some park NR staff that have expressed interest in the ability to easily monitor a "live feed" of recent iNaturalist and eBird observations made in the park.  I'm told by the Park's avian biologist that a rare bird species observation was reported in the park, but the observation went unnoticed until months later.  I can imagine something like this displayed in an internal "dashboard" application.

**Public/Interp Staff**
When parks run a BioBlitz event, they could use builder to create a public facing web map that would display the observations made by the BioBlitz participants. Such a map can be embedded in an nps.gov page via a CMS element, or linked to in a social media post. 

I know Simon mentioned something about visualizations being done for the Centennial BioBlitz events but I don't know the details.  I'd be interested in knowing if it is just a one-off for the Centennial or if it is able to be updated or used for future BioBlitz events after the Centennial?

**Comment by tpcolson** [comment]
We'd like to be able to view IN observation locations superimposed on an authoritative and accurate map that are occurring inside the park.

**Comment by llnelson** [comment]
Just want to confirm that the preset will be add-able as an option in Builder - is this correct?

**Comment by nateirwin** [comment]
Correct, @llnelson. This would act just like the Places preset in Builder (screenshot attached).

Basically you would click on an "iNaturalist" button, select a few configuration options (park, etc.), and then the form would pre-fill with the information needed to add the overlay to the map. Sounds like we could just bring it in as KML.

**Comment by nateirwin** [comment]
@simonkingston and @llnelson: @ryanjhodge created a pull request to add this to Builder, but there is one enhancement that would be nice to make before merging and deploying it. Right now, to add an iNaturalist project, you have to know the id of the project and type it in manually. You can find the id in the URL of a project's page on the iNaturalist website (e.g. for http://www.inaturalist.org/projects/arches-national-park the project id is `arches-national-park`).

Do you all know of a way to get a list of NPS iNaturalist projects? We took a look at the [project endpoint](https://www.inaturalist.org/pages/api+reference#get-projects), but it only returns a paged dataset of projects, and there isn't a way to just get NPS projects.

**Comment by simonkingston** [comment]
@nateirwin I don't know of a way to pull NPS iNaturalist projects.  We're going to work to tag/attribute the projects we create for the Centennial BioBlitzes so that they're easy to pull, but for any existing projects, I'm not sure how you'd do it.

**Comment by ryanjhodge** [comment]
Just revisited this, the `source` param of the `project/:id` endpoint looked promising but I don't see a way of setting a project's `source` value.  I even tried creating a test project under my account and I didn't see any source attribute fields for new projects.  Furthermore, all the existing projects have zero length string or null set for their `source_url` attribute.  Perhaps it's some kind of legacy field or for projects that were imported into iNaturalist.

There is a [`project/user/:login` endpoint](https://www.inaturalist.org/pages/api+reference#get-projects-user-login) which returns all projects for a certain user.  So if the projects are all made under the same username that would be a way of accomplishing this.  We could use a regex expression on the results list to filter on the tag/attribute or naming convention that @simonkingston just mentioned.

**Comment by nateirwin** [comment]
I went ahead and merged/deployed. We can refine this in the future if better data about projects becomes available. Here's a test map I created: http://www.nps.gov/maps/full.html?mapId=d808985c-1611-4621-b7d0-7c9a3705b2ca.

I switched from the `kml` endpoint to the `csv` endpoint, as it exposes more data.

Great stuff, y'all!

**Comment by ryanjhodge** [comment]
Good catch on the CSV end point! :mag: Map looks fantastic!
