### ISSUE TITLE
Discrepancy between latest version of map and link to the map

### ISSUE THREAD

**Issue by frogmapr** [nationalparkservice/npmap-builder#253]
The link on the builder site takes me to an old version of my map even though it has been updated and I have deleted my browser cache to the beginning of time.  
[http://www.nps.gov/maps/full.html?mapId=6796e967-0c84-45dc-99e8-c5cb0f715528](url)

For instance in the editor my title looks like this:
![image](https://cloud.githubusercontent.com/assets/11652263/12896597/001c85de-ce60-11e5-82ec-ac03acf7a1cd.png)
But when I load the linked page the title looks like this (old version):
![image](https://cloud.githubusercontent.com/assets/11652263/12896610/161f454c-ce60-11e5-912c-fdd7c425235a.png)

How can I resolve this discrepancy between my latest map and the link?

Thanks!

**Comment by frogmapr** [comment]
I just tried the link again and it is now up to date, is there sometimes a lag between when the updates get pushed to the live link?

**Comment by nateirwin** [comment]
Yes, there can be a lag. Builder publishes maps via Akamai, the National Park Service's content delivery network provider, so changes made to maps have to be purged from the cache. This can take up to ten minutes.
