### ISSUE TITLE
Make Park Tiles 3 available as basemap

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/npmap-builder#255]
I think it's time we make PT3 available as a basemap in Builder. We won't make it the default quite yet, but parks that have put a lot of work into their data (I'm looking at you, @tpcolson) should be able to use it if they feel comfortable with where it's at.

Thoughts, @mtaylorlong?

**Comment by mtaylorlong** [comment]
I'm all for adding it as a basemap in Builder. As long as we don't freak anyone else out, it doesn't freak me out. :)

**Comment by nateirwin** [comment]
I guess the main question I have is: Are we ever going to "default" Builder/NPMap.js maps to Park Tiles 3? Or are we going to always default to Park Tiles 2 and make people manually add Park Tiles 3 to their maps?

Seems like we should probably stick with Park Tiles 2 as the default for now - at least we have wider buy-in/approval of switching to Park Tiles 3.

**Comment by nateirwin** [comment]
Cc/ @jimmyrocks @jakecoolidge @cwlawlis802

**Comment by jakecoolidge** [comment]
I figured that someday in the future, Park Tiles 3 would replace PT2, and PT2 might even go away. In that scenario, PT3 would be the default, but we haven't gotten there yet.

**Comment by nateirwin** [comment]
Done
