### ISSUE TITLE
Selecting clustering option prevents GeoJSON overlay from loading.

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/npmap-builder#259]
When adding a GeoJSON overlay to Builder, if the clustering checkbox is selected, both the Save Overlay and Cancel boxes are grayed out after clicking Save Overlay. X-ing out of the window is the only way to return to the map.

<img width="613" alt="screen shot 2016-03-23 at 4 28 19 pm" src="https://cloud.githubusercontent.com/assets/11392872/14002875/6b670158-f114-11e5-9897-deb625257d60.png">

<img width="629" alt="screen shot 2016-03-23 at 4 28 36 pm" src="https://cloud.githubusercontent.com/assets/11392872/14002881/740d07bc-f114-11e5-9d79-d28c083aa1a8.png">

after Save Overlay has been clicked:
<img width="626" alt="screen shot 2016-03-23 at 4 28 49 pm" src="https://cloud.githubusercontent.com/assets/11392872/14002883/7bd11682-f114-11e5-8f0d-fe7a989f6ec4.png">

**Comment by nateirwin** [comment]
Thanks for reporting @jakecoolidge!

**Comment by jakecoolidge** [comment]
I'll let Anne know; she'll be glad to have this working!
