### ISSUE TITLE
NPS.gov "More info" link broken

### ISSUE THREAD

**Issue by cwlawlis802** [nationalparkservice/npmap-builder#264]
![builder_more_info](https://cloud.githubusercontent.com/assets/1238636/16089087/e0a9a010-32e6-11e6-9620-dd865fe6b928.png)

Currently links to https://sites.google.com/a/nps.gov/web-community/training/guides-manuals/guide-npmap but should link to https://sites.google.com/a/nps.gov/web-community/how-to/guides-manuals/guide-npmap.

**Comment by cwlawlis802** [comment]
Done via https://github.com/nationalparkservice/npmap-builder/commit/04efb695017199d7d1e12a292a527e2fc04f81cf

**Comment by cwlawlis802** [comment]
This change does not seem to appear in https://github.com/nationalparkservice/npmap-builder/tree/dee5c066a5f45dfa920f27afa24e734648db9bb0 which is synced with https://github.com/nationalparkservice/insidemaps/tree/master/v2/builder.

Reopening - will close once this change goes live.

**Comment by nateirwin** [comment]
Done. The change was committed/merged into master just fine.

**Comment by cwlawlis802** [comment]
Huh, weird that it took so long to show up.

So what's the difference between Master and this tree https://github.com/nationalparkservice/npmap-builder/tree/dee5c066a5f45dfa920f27afa24e734648db9bb0 that is linked to https://github.com/nationalparkservice/insidemaps/tree/master/v2/builder @nateirwin? My merge went live to Master but it didn't show up in that tree, which is what caused my confusion.

**Comment by nateirwin** [comment]
Honestly, I'm not sure what's going on there.
