### ISSUE TITLE
Printing omitting point of interest pins

### ISSUE THREAD

**Issue by cwlawlis802** [nationalparkservice/npmap-builder#267]
From Nathan @ NCR:

> When printing an NP Map, it's omitting the pins. Can you look into it? We're working on http://insidemaps.nps.gov/builder/map/?mapId=062ccd8f-7470-40f3-83c3-9cff2c06f85d

**Comment by nateirwin** [comment]
Tracking here: https://github.com/nationalparkservice/npmap.js/issues/381. Going to close this one.
